resolver: lts-19.6

packages:
- .

extra-deps:
- pretty-terminal-0.1.0.0@sha256:e9135d86ebb2a8e3aaf5a79088de4628dbd49988388e0fbfc26c5ecb3c399ad9,1638

nix:
  packages:
  # hopefully theses libraries are in the stack global environment
    - pcre
    - zlib
