name: Complete CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v10
      with:
        name: guibou
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # Builds cabal (nix)
    - name: Build with all supported GHC
      run: nix-build -A krank_all

  stack_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Stack
      run: sudo apt-get install haskell-stack

    # Build stack
    - name: Stack 8.10
      run: stack --resolver lts-19.6 test
